### ISSUE TITLE
The provided init.lua is probably outdated

### ISSUE THREAD

**Issue by OJarrisonn** [Rolv-Apneseth/starship.yazi#1]
Following the installation steps and trying to run yazi raises:

```
thread 'main' panicked at /home/ojarrisonn_/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yazi-plugin-0.2.3/src/plugin.rs:45:32:
called `Result::unwrap()` on an `Err` value: RuntimeError("[string \"/home/ojarrisonn_/.cargo/registry/src/index.c...\"]:32: attempt to perform arithmetic on a nil value (field 'SYNC_CALLS')\nstack traceback:\n\t[C]: in metamethod 'add'\n\t[string \"/home/ojarrisonn_/.cargo/registry/src/index.c...\"]:32: in field 'sync'\n\t.../ojarrisonn_/.config/yazi/plugins/starship.yazi/init.lua:1: in main chunk\n\t[C]: in function 'require'\n\t[string \"/home/ojarrisonn_/.cargo/registry/src/index.c...\"]:1: in main chunk")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

In clear, the error message: 
```
[string \"/home/ojarrisonn_/.cargo/registry/src/index.c...\"]:32: attempt to perform arithmetic on a nil value (field 'SYNC_CALLS')
stack traceback:
    [C]: in metamethod 'add'
    [string \"/home/ojarrisonn_/.cargo/registry/src/index.c...\"]:32: in field 'sync'
    .../ojarrisonn_/.config/yazi/plugins/starship.yazi/init.lua:1: in main chunk
    [C]: in function 'require'
    [string \"/home/ojarrisonn_/.cargo/registry/src/index.c...\"]:1: in main chunk
```

Lot of doc is outdated both for Yazi and it's plugins

**Comment by Rolv-Apneseth** [comment]
Thanks for opening this, I'll have a look when I get a chance later

**Comment by Rolv-Apneseth** [comment]
What is your `yazi` version and how did you install actually, as I haven't come across this error

**Comment by Rolv-Apneseth** [comment]
I was using latest git changes, but I went and tried the latest stable version of [v0.2.4](https://github.com/sxyazi/yazi/releases/tag/v0.2.4), (it is also up to date on [crates.io](https://crates.io/crates/yazi-fm)), and it still works for me. Could you make sure you are on the latest stable version?

**Comment by OJarrisonn** [comment]
Sorry for the waiting.

I'm using `yazi` 0.2.3 and i've iinstalled it usng `cargo install`. I didn't managed to update yazi to 0.2.4, it simply doesn't compiles `yazi-adaptor`

**Comment by OJarrisonn** [comment]
I don't think so

**Comment by Rolv-Apneseth** [comment]
> I don't think so

Could you try installing it with that command and see if the problem persists?

**Comment by OJarrisonn** [comment]
Just updated to 0.2.4 and now it works perfctly, thanks

**Comment by Rolv-Apneseth** [comment]
That's good to hear. I might add a note to the readme about the minimum version just in case.
