### ISSUE TITLE
Prompt is not updated in real time when performing modifications inside a git directory.

### ISSUE THREAD

**Issue by Alexey104** [Rolv-Apneseth/starship.yazi#11]
When performing any modifications inside a git directory you are currently in (switching branches, modifying/deleting files etc.), either from Yazi itself or from the outside, the prompt does not change and remains static until you go out of this directory and return back. Is it possible to force the prompt to update in real time?

**Comment by Rolv-Apneseth** [comment]
Off the top of my head I can't see how that would be achieved without just re-running the prompt on a timer. I could look into maybe providing that as an option? Couldn't do it by default as it would hurt performance for everyone

**Comment by Alexey104** [comment]
Thank you for the response! 


> Off the top of my head I can't see how that would be achieved without just re-running the prompt on a timer. I could look into maybe providing that as an option?

I don't think it's worth your time. This is not a feature request, just a question. I just recently switched from Ranger to Yazi indeed because of performance, I'm not very fluent in Lua and just wanted to clarify if I missed or misconfigured something. If this is by design, that's OK. The idea with a timer really sounds like an overkill, so let's just leave things as they are.

Cheers!
