### ISSUE TITLE
Seems to be broken on NixOS

### ISSUE THREAD

**Issue by ArtemChandragupta** [Rolv-Apneseth/starship.yazi#2]
Having done the above, I got an empty transparent header:
![image](https://github.com/Rolv-Apneseth/starship.yazi/assets/90765302/b8aca941-e3f6-4320-b12b-e7a1a4734504)

Perhaps this is due to the peculiarity of symlinks in NixOS, or maybe the fact is that my promt is drawn on two lines and uses a colored background:
![image](https://github.com/Rolv-Apneseth/starship.yazi/assets/90765302/e307ddcc-173d-491e-ab20-63fc08cc1026)

**Comment by Rolv-Apneseth** [comment]
Could you share your `starship.toml`? I don't run NixOS but I'd like to see if I can replicate it

**Comment by ArtemChandragupta** [comment]
Thank you for a fast reply.

This is recolored [gruvbox-recolored preset](https://starship.rs/presets/gruvbox-rainbow). I can't give you my exact TOML, because it is written in Nix and it is useless without NixOS

**Comment by ArtemChandragupta** [comment]
Oh, i just get it working by adding NixOS module in addition to Home manager module. But it looks terrible 
![image](https://github.com/Rolv-Apneseth/starship.yazi/assets/90765302/c869eba7-612b-4070-a909-996d1a0517d9)

**Comment by Rolv-Apneseth** [comment]
> This is recolored [gruvbox-rainbow preset](https://starship.rs/presets/gruvbox-rainbow). I can't give you my exact TOML, because it is written in Nix and it is useless without NixOS

Ah ok, does `home-manager` or whatever you're using not output the resulting `starship.toml` file somewhere? Anyway, yes using that preset that is about how it looks for me.

The header is just taking up one row, and if the background is filled in like for that preset, it will be touching the background of the line below. The only fix I can think of for the appearance would be a full empty line beneath the prompt, which I'm not sure `Yazi` allows but I'll have a look.

**Comment by Rolv-Apneseth** [comment]
Hey, I think I'm gonna include a snippet on the README without the border, but you can actually use the [full border tip]() from `Yazi` itself to achieve this if you don't mind the border:

![header](https://github.com/Rolv-Apneseth/starship.yazi/assets/69486699/96f5d0d3-e9e3-4c91-8d00-29237c941744)

Just paste this code into your `init.lua`, which overrides the base UI's `Manager:render` method:

```lua
        function Manager:render(area)
            local chunks = self:layout(area)

            local bar = function(c, x, y)
                x, y = math.max(0, x), math.max(0, y)
                return ui.Bar(
                    ui.Rect({
                        x = x,
                        y = y,
                        w = ya.clamp(0, area.w - x, 1),
                        h = math.min(1, area.h),
                    }),
                    ui.Bar.TOP
                ):symbol(c)
            end

            return ya.flat({
                -- Borders
                ui.Border(area, ui.Border.ALL):type(ui.Border.ROUNDED),
                ui.Bar(chunks[1], ui.Bar.RIGHT),
                ui.Bar(chunks[3], ui.Bar.LEFT),

                bar("┬", chunks[1].right - 1, chunks[1].y),
                bar("┴", chunks[1].right - 1, chunks[1].bottom - 1),
                bar("┬", chunks[2].right, chunks[2].y),
                bar("┴", chunks[2].right, chunks[1].bottom - 1),

                -- Parent
                Parent:render(chunks[1]:padding(ui.Padding.xy(1))),
                -- Current
                Current:render(chunks[2]:padding(ui.Padding.y(1))),
                -- Preview
                Preview:render(chunks[3]:padding(ui.Padding.xy(1))),
            })
        end
```

**Comment by ArtemChandragupta** [comment]
Thanks. Is there any method to change the color of this border?

Or, ideally, can you make frame color identical to terminal background, as long as intercolumn borders are grey?

**Comment by Rolv-Apneseth** [comment]
Not sure but I think that would make the divisions between the columns do that too. I'm gonna figure out/ see if it's possible to do that padding without the border later and I'll update here

**Comment by Rolv-Apneseth** [comment]
So like this works:

![no_columns](https://github.com/Rolv-Apneseth/starship.yazi/assets/69486699/1cb4db06-5b52-4f2b-8ef5-e74d537c70ce)

```lua
function Manager:render(area)
    local chunks = self:layout(area)

    local bar = function(c, x, y)
        x, y = math.max(0, x), math.max(0, y)
        return ui.Bar(
            ui.Rect({
                x = x,
                y = y,
                w = ya.clamp(0, area.w - x, 1),
                h = math.min(1, area.h),
            }),
            ui.Bar.TOP
        ):symbol(c)
    end

    return ya.flat({
        -- Borders
        ui.Bar(chunks[1], ui.Bar.RIGHT)
            :symbol(THEME.manager.border_symbol)
            :style(THEME.manager.border_style),
        ui.Bar(chunks[3], ui.Bar.LEFT)
            :symbol(THEME.manager.border_symbol)
            :style(THEME.manager.border_style),

        bar(" ", chunks[1].right - 1, chunks[1].y),
        bar(" ", chunks[2].right, chunks[2].y),

        -- Parent
        Parent:render(chunks[1]:padding(ui.Padding.xy(1))),
        -- Current
        Current:render(chunks[2]:padding(ui.Padding.y(1))),
        -- Preview
        Preview:render(chunks[3]:padding(ui.Padding.xy(1))),
    })
end
```
---

I kind of find it cool with the columns though:

![columns](https://github.com/Rolv-Apneseth/starship.yazi/assets/69486699/74d639d3-60c3-492e-b176-d207a12c2506)

```lua
function Manager:render(area)
    local chunks = self:layout(area)

    local bar = function(c, x, y)
        x, y = math.max(0, x), math.max(0, y)
        return ui.Bar(
            ui.Rect({
                x = x,
                y = y,
                w = ya.clamp(0, area.w - x, 1),
                h = math.min(1, area.h),
            }),
            ui.Bar.TOP
        ):symbol(c)
    end

    return ya.flat({
        -- Borders
        ui.Bar(chunks[1], ui.Bar.RIGHT)
            :symbol(THEME.manager.border_symbol)
            :style(THEME.manager.border_style),
        ui.Bar(chunks[3], ui.Bar.LEFT)
            :symbol(THEME.manager.border_symbol)
            :style(THEME.manager.border_style),

        bar("┬", chunks[1].right - 1, chunks[1].y),
        bar("┴", chunks[1].right - 1, chunks[1].bottom - 1),
        bar("┬", chunks[2].right, chunks[2].y),
        bar("┴", chunks[2].right, chunks[1].bottom - 1),

        -- Parent
        Parent:render(chunks[1]:padding(ui.Padding.xy(1))),
        -- Current
        Current:render(chunks[2]:padding(ui.Padding.y(1))),
        -- Preview
        Preview:render(chunks[3]:padding(ui.Padding.xy(1))),
    })
end
```

**Comment by ArtemChandragupta** [comment]
Thank you very much for this method! I think this could be posted on the tips page in the Yazu documentation.
As for me, I think both options with and without frames are really fascinating.
![image](https://github.com/Rolv-Apneseth/starship.yazi/assets/90765302/87dd22bb-cfa4-4acc-a8ea-c8104b7432b0)

**Comment by Rolv-Apneseth** [comment]
Clean setup btw
