### ISSUE TITLE
Any way starship works only for yazi

### ISSUE THREAD

**Issue by AnirudhG07** [Rolv-Apneseth/starship.yazi#5]
I have powerlevel10k installed for my usual terminal. But I just somehow like the fact of having starship in yazi.

Is there anyway I can have starship just for yazi??

## Configs
MacOS, yazi(latest built from source, like today)
iTerm, zsh

## What I have done so far
I have added starship.toml with this [preset](https://starship.rs/presets/nerd-font) in my ~/.config/starship.toml and also I have downloaded starship.yazi

**Comment by Rolv-Apneseth** [comment]
This plugin just calls `starship` directly, so it should work. Do you have `starship` on your `$PATH`? What is the output of `starship --version`?

**Comment by AnirudhG07** [comment]
starship 1.19.0
branch:
commit_hash:
build_time:2024-05-15 17:06:13 +00:00
build_env:rustc 1.78.0 (9b00956e5 2024-04-29) (Homebrew),

**Comment by Rolv-Apneseth** [comment]
And nothing happens when you use `starship.yazi`? Strange. Just checking, does `starship prompt` actually output anything?

**Comment by AnirudhG07** [comment]
<img width="443" alt="image" src="https://github.com/user-attachments/assets/e8209ef5-995a-4502-b66e-824bfdeb3b24">

Error comes - 
```bash
Error: Lua runtime failed

Caused by:
    No such file or directory (os error 2)
    stack traceback:
    	[C]: in function 'require'
    	[string "init.lua"]:4: in main chunk
```
This happens when I put below in my init.lua
```lua
require("starship"):setup()
```
You can see my starship [dotfiles](https://github.com/AnirudhG07/dotfiles/blob/stow/yazi/.config/yazi/plugins/starship.yazi/init.lua) for anything particular

**Comment by Rolv-Apneseth** [comment]
So strange, I can't reproduce. Your `yazi` config works fine for me:

![yazi](https://github.com/user-attachments/assets/25e1c103-e1f4-49d3-a09b-b22b441bd36d)

Maybe it's something Mac specific? I'm not even sure if the error means it happened within the plugin or just that it somehow couldn't find it. Would you mind replacing the code in `starship.yazi/init.lua` with some other plugins code just to verify that?

**Comment by AnirudhG07** [comment]
I mean all other plugins just work fine. I'll maybe reinstall starship and start everything from scratch. Maybe that would work.

**Comment by AnirudhG07** [comment]
Your suggestion actually freakin worked.

**Comment by Rolv-Apneseth** [comment]
Oh so it's working now?

**Comment by AnirudhG07** [comment]
yep.

**Comment by Rolv-Apneseth** [comment]
Nice, glad it's working for you then
