### ISSUE TITLE
Prompt not updated when switching tabs

### ISSUE THREAD

**Issue by pawel-szopinski** [Rolv-Apneseth/starship.yazi#6]
When I have multiple tabs open and all of them are in different directory, the starship prompt is not being updated after tab is changed. This issue does not exist if the plugin is disabled, e.g. yazi, by default, updates path in top left corner every time the tab is switched.

Also, is there a way to have custom starship config only for yazi? I know one can choose specific starship config by exporting STARSHIP_CONFIG env var.

**Comment by Rolv-Apneseth** [comment]
I don't use tabs and never noticed, so thanks for opening this. I'll have a look at that and also possibly allowing a config file to be specified.

**Comment by Rolv-Apneseth** [comment]
I opened an issue over at `Yazi` itself to see if I can get something for subscribing to tab changing events, so we'll see how that goes.

As for the configuration file, could you check out if the changes over on [this branch](https://github.com/Rolv-Apneseth/starship.yazi/tree/configuration-file) work well for you? Should be something like the following command to just grab that branch:

```bash
git clone -b configuration-file https://github.com/Rolv-Apneseth/starship.yazi.git ~/.config/yazi/plugins/starship.yazi
```

**Comment by pawel-szopinski** [comment]
I've just reviewed the changes and it works like a charm. Will you be merging it to main branch?

Let's see how it goes with the tab switching.

Thank you very much!

**Comment by Rolv-Apneseth** [comment]
I'll merge it into the main branch yeah, was just waiting to see if it worked for you.

> Thank you very much!

No problem and yeah I'll comment here again when there's an update about the tabs

**Comment by Rolv-Apneseth** [comment]
`Yazi` got a new event for switching tabs and I made the changes required for this plugin in #10. That should work with the latest changes of both, let me know if there are any issues

**Comment by mikavilpas** [comment]
Works nicely, thanks for the fix 🙂

**Comment by pawel-szopinski** [comment]
It works for me as well. Thank you very much!

**Comment by Rolv-Apneseth** [comment]
> Works nicely, thanks for the fix 🙂

Thanks for creating the new event in `Yazi`
